baseURL = "https://realjf.io/"
languageCode = "en-us"
title = "Real_JF's blog"
theme = "m10c"
paginate = "20"

[params]
  author = "realjf"
  description = "认识自己，接受自己，忘记自己，追随自己的灵魂"
  [[params.social]]
    name = "github"
    url = "https://github.com/realjf"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/realjf2"
  [[params.social]]
    name = "blog"
    url = "http://realjf.com"

[menu]
  [[menu.main]]
    identifier = "golang"
    name = "golang language"
    title = "golang language"
    url = "/golang/"
    weight = -110
  [[menu.main]]
    identifier = "kubernetes"
    name = "kubernetes"
    title = "kubernetes"
    url = "kubernetes"
    weight = 100
