baseURL = "https://realjf.io/"
languageCode = "en-us"
title = "Real_JF's blog"
theme = "m10c"
paginate = "10"

[params]
  author = "realjf"
  description = "认识自己，接受自己，忘记自己，追随自己的灵魂"
  [[params.social]]
    name = "github"
    title = "github"
    url = "https://github.com/realjf"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/realjf2"
  [[params.social]]
    name = "activity"
    url = "http://bbs.realjf.com"

[menu]
  [[menu.main]]
    identifier = "golang"
    name = "golang"
    title = "golang"
    url = "/golang/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 100
  [[menu.main]]
    identifier = "kubernetes"
    name = "kubernetes"
    title = "kubernetes"
    url = "/kubernetes/"
  [[menu.main]]
    identifier = "docker"
    name = "docker"
    title = "docker"
    url = "/docker/"
  [[menu.main]]
    identifier = "ceph"
    name = "ceph"
    title = "ceph"
    url = "/ceph/"
  [[menu.main]]
    identifier = "linux"
    name = "linux"
    title = "linux"
    url = "/linux/"
  [[menu.main]]
    identifier = "distributed system"
    name = "分布式"
    title = "分布式"
    url = "/distributedsystem/"
  [[menu.main]]
    identifier = "tools"
    name = "tools"
    title = "工具"
    url = "/tools/"
  [[menu.main]]
    identifier = "streaming"
    name = "streaming"
    title = "直播"
    url = "/streaming/"
  [[menu.main]]
    identifier = "GC"
    name = "garbagecollection"
    title = "垃圾回收(garbage collection)"
    url = "/gc/"
  [[menu.main]]
    identifier = "ruby"
    name = "ruby"
    title = "ruby"
    url = "/ruby/"
  [[menu.main]]
    identifier = "wechat"
    name = "微信"
    title = "微信"
    url = "/wechat/"
  [[menu.main]]
    identifier = "nginx"
    name = "nginx"
    title = "nginx"
    url = "/nginx/"
  [[menu.main]]
    identifier = "python"
    name = "python"
    title = "python"
    url = "/python/"