baseURL = "https://realjf.io/"
languageCode = "en-us"
title = "Real_JF's blog"
theme = "m10c"
paginate = "20"

[params]
  author = "realjf"
  description = "认识自己，接受自己，忘记自己，追随自己的灵魂"
  [[params.social]]
    name = "github"
    title = "github"
    url = "https://github.com/realjf"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/realjf2"
  [[params.social]]
    name = "activity"
    url = "http://realjf.com"

[menu]
  [[menu.main]]
    identifier = "golang"
    name = "golang"
    title = "golang"
    url = "/golang/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 100
  [[menu.main]]
    identifier = "kubernetes"
    name = "kubernetes"
    title = "kubernetes"
    url = "/kubernetes/"
  [[menu.main]]
    identifier = "docker"
    name = "docker"
    title = "docker"
    url = "/docker/"
  [[menu.main]]
      identifier = "ceph"
      name = "ceph"
      title = "ceph"
      url = "/ceph/"
